using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Account
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AccountTests
    {
        private Account instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new Account();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of Account
        /// </summary>
        [Test]
        public void AccountInstanceTest()
        {
            Assert.IsInstanceOf<Account> (instance, "instance is a Account");
        }

        
        /// <summary>
        /// Test the property 'Balance' 
        /// </summary>
        [Test]
        public void BalanceTest()
        {
            // TODO: unit test for the property 'Balance' 
        }
        
        /// <summary>
        /// Test the property 'AccountType' 
        /// </summary>
        [Test]
        public void AccountTypeTest()
        {
            // TODO: unit test for the property 'AccountType' 
        }
        

    }

}
