using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DefaultApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DefaultApiTests
    {
        private DefaultApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
           instance = new DefaultApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DefaultApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            Assert.IsInstanceOf<DefaultApi> (instance, "instance is a DefaultApi");
        }

        
        /// <summary>
        /// Test UsersUserIdAccountGet
        /// </summary>
        [Test]
        public void UsersUserIdAccountGetTest()
        {
            // TODO: add unit test for the method 'UsersUserIdAccountGet'
            string userId = null; // TODO: replace null with proper value
            
            var response = instance.UsersUserIdAccountGet(userId);
            Assert.IsInstanceOf<Account> (response, "response is Account"); 
        }
        
    }

}
